spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.devtools.restart.enabled=false

roboflow.api.key=${ROBOFLOW_API_KEY}
roboflow.model=${ROBOFLOW_MODEL}
roboflow.base.url={ROBOFLOW_BASE_URL}

openai.api.key=${OPENAI_API_KEY}
openai.base.url=${OPENAI_BASE_URL}
openai.model=${OPENAI_MODEL}