spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

spring.devtools.restart.enabled=false

roboflow.api.key=${ROBOFLOW_API_KEY}
roboflow.model=${ROBOFLOW_MODEL}
roboflow.base.url=${ROBOFLOW_BASE_URL}

openai.api.key=${OPENAI_API_KEY}
openai.base.url=${OPENAI_BASE_URL}
openai.model=${OPENAI_MODEL}

spring.web.resources.static-locations=file:/app/static/

# Mailpit Configuration (SMTP local - solo para testing)
spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# App base URL
app.base.url=https://api-gymbromachine.codelordo.com